image: 'registry.fedoraproject.org/fedora:31'

before_script:
  - dnf update -y
  - dnf install -y rust cargo git meson ninja-build libsoup-devel glib2-devel gobject-introspection-devel xorg-x11-server-Xvfb
  - git submodule update --init

stages:
  - test
  - deploy

build:
  stage: test
  script:
    - cargo build --all-features
    # - xvfb-run -a -s "-screen 0 1024x768x24" cargo test

pages:
  stage: deploy
  script:
    - cargo doc -p soup --all-features --no-deps
    - mv target/doc/ public
  artifacts:
    paths:
      - public
  only:
    refs:
      - master
