// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

#[cfg(any(feature = "v2_40", feature = "dox"))]
use gio;
use glib::object::IsA;
use glib::translate::*;
use soup_sys;
use std::fmt;
use Request;

glib_wrapper! {
    pub struct RequestFile(Object<soup_sys::SoupRequestFile, soup_sys::SoupRequestFileClass, RequestFileClass>) @extends Request;

    match fn {
        get_type => || soup_sys::soup_request_file_get_type(),
    }
}

pub const NONE_REQUEST_FILE: Option<&RequestFile> = None;

pub trait RequestFileExt: 'static {
    #[cfg(any(feature = "v2_40", feature = "dox"))]
    fn get_file(&self) -> Option<gio::File>;
}

impl<O: IsA<RequestFile>> RequestFileExt for O {
    #[cfg(any(feature = "v2_40", feature = "dox"))]
    fn get_file(&self) -> Option<gio::File> {
        unsafe {
            from_glib_full(soup_sys::soup_request_file_get_file(self.as_ref().to_glib_none().0))
        }
    }
}

impl fmt::Display for RequestFile {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "RequestFile")
    }
}
